"""update resume nullable

Revision ID: 4769e64b2170
Revises: d353d9d4f6dc
Create Date: 2026-07-02 22:32:11.218491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4769e64b2170'
down_revision: Union[str, Sequence[str], None] = 'd353d9d4f6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'resume_text',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'resume_text',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
