"""update resume column

Revision ID: d353d9d4f6dc
Revises: 64b973790016
Create Date: 2026-07-02 22:07:33.090171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd353d9d4f6dc'
down_revision: Union[str, Sequence[str], None] = '64b973790016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('stored_file_name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'stored_file_name')
    # ### end Alembic commands ###
